### ISSUE TITLE
DigiByte v8.22.0 Beta MVP To Do Task List

### ISSUE THREAD

**Issue by JaredTate** [DigiByte-Core/digibyte#87]
I want to thank everyone for the hard work they have put into the upcoming DGB 8.22.0 client. Over the past 6 months, there has been a tremendous amount of effort poured into 8.22.0. 

This will be the largest, most reviewed, and most tested release ever made for DGB. We will also have the most complete release ever as well. Now that we are on the verge of completing the upstream BTC 8.22 merge into our "develop" branch it is important we have a checkoff list so everyone in the community is on the same page as to what is needed. 

Here is an initial list, if you have more please mention it and it will be added. The idea is so everyone is on the same page as to what a Minimum Viable Product looks like for 8.22 with remaining tasks.

Note: To those non devs reading this as development progress update, please understand there are 1000s of individual tasks already completed during the upstream BTC merge prior to this final list being drafted. At time of this writing there are +281,173 lines of code added and −92,788 lines of code removed in the 8.22 PR contained in 2,286 commits. That is a massive amount of work.

- [x] TODO-01: Merge https://github.com/DigiByte-Core/digibyte/tree/feature/8.22.0 into https://github.com/DigiByte-Core/digibyte/tree/develop
     - [x] Ensure no merge conflicts from feature branch to develop
     - [x] Setup Dandelion Feature branch
     - [x] Setup Fix Functional Tests Feature Branch
     - [x] Setup Fee Feature Branch
     - [ ] Setup Algo Swap Feature Branch
     - [ ] Setup GUI/ Theme Feature Branch 
     - [ ] Setup Supply Curve/ Limit Feature Branch 
     - [x] Setup Client Speed / Optimize Loadup feature branch
- [ ] TODO-02: Confirm Dandelion Working Properly
     - [x] Validate Dandelion is really disabled when using -disable-dandelion arg & non-dandelion transactions can be sent.
     - [ ] Validate Dandelion is enabled (i.e. dandelion thread is starting) when not specifying -disable-dandelion arg 
     - [ ] Validate Dandelion is enabled & correctly broadcasting a dandelion transaction (observe logs!!). Ensure that the transaction eventually transitions from the stempool into the real mempool.
     - [x] Validate Dandelion is enabled but normal transactions are still possible
- [x] TODO-03: Confirm MultiAlgo Mining Working Properly
     - [x] Mine sha256 block
     - [x] Mine odocrypt block 
     - [x] Mine Qubit block
     - [x] Mine Skien block
     - [x] Mine Scrypt block
- [x] TODO-04: Confirm All DGB Chain Specific Settings Set Properly
     - [x] Confirm Buried Deployments
     - [x] Confirm Ports
     - [x] Confirm Protocol Version
     - [x] Confirm Client Version
     - [x] Confirm Seeds
     - [x] Confirm Checkpoints 
- [ ] TODO-05: Confirm Taproot Deployment Set Properly & Tested
     - [x]  Set Taproot Activation Window
     - [ ] Test Taproot Activation
- [ ] TODO-06: Confirm DGB Signet Added Properly
     - [ ] Set initial parameters
     - [ ] Test Signet
- [ ] TODO-07: Confirm 8.22 DGB GUI Working As Expecting
     - [x] Confirm Theme & Icons
     - [x] Confirm Send Coins Page
     - [x] Confirm Home Screen
     - [x] Update Version Image
     - [x] Confirm Receive Page
     - [x] Test GUI Multi Wallet Feature
- [x] TODO-08: Confirm DGB Testnet Setup Properly & Reset
     - [x] Reset Testnet
     - [x] Test mine all algos
     - [ ] Test taproot activation
- [x] TODO-09: Finalize TX Fee Policy for DGB v8.22
     - [x]  Remove RBF
     - [x]  Determine Minimum DGB TX Fee
     - [x] Test Fee Estimates
- [x] TODO-10:  Fix All Unit Tests
- [x] TODO-11:  Fix All Functional Tests
- [x] TODO-12:  Fix All Util & Fuzz Tests
- [ ] TODO-12:  Finalize Supply Curve / Distribution Hard Cap Code
- [x] TODO-13:  Optimize Initial Client Load Up Speed

**Comment by bosszhit4l69** [comment]
> I want to thank everyone for the hard work they have put into the upcoming DGB 8.22.0 client. Over the past 6 months, there has been a tremendous amount of effort poured into 8.22.0.
> 
> This will be the largest, most reviewed, and most tested release ever made for DGB. We will also have the most complete release ever as well. Now that we are on the verge of completing the upstream BTC 8.22 merge into our "develop" branch it is important we have a checkoff list so everyone in the community is on the same page as to what is needed.
> 
> Here is an initial list, if you have more please mention it and it will be added. The idea is so everyone is on the same page as to what a Minimum Viable Product looks like for 8.22 with remaining tasks.
> 
> Note: To those non devs reading this as development progress update, please understand there are 1000s of individual tasks already completed during the upstream BTC merge prior to this final list being drafted. At time of this writing there are +281,173 lines of code added and −92,788 lines of code removed in the 8.22 PR contained in 2,286 commits. That is a massive amount of work.
> 
> * [ ]  TODO-01: Merge https://github.com/DigiByte-Core/digibyte/tree/feature/8.22.0 into https://github.com/DigiByte-Core/digibyte/tree/develop
>   
>   * [x]  Ensure no merge conflicts from feature branch to develop
>   * [ ]  Setup Dandelion Feature branch
>   * [ ]  Setup Fix Functional Tests Feature Branch
>   * [ ]  Setup Fee Feature Branch
>   * [ ]  Setup Algo Swap Feature Branch
>   * [ ]  Setup GUI/ Theme Feature Branch
>   * [ ]  Setup Supply Curve/ Limit Feature Branch
>   * [ ]  Setup Client Speed / Optimize Loadup feature branch
> * [ ]  TODO-02: Confirm Dandelion Working Properly
>   
>   * [ ]  Validate Dandelion is really disabled when using -disable-dandelion arg & non-dandelion transactions can be sent.
>   * [ ]  Validate Dandelion is enabled (i.e. dandelion thread is starting) when not specifying -disable-dandelion arg
>   * [ ]  Validate Dandelion is enabled & correctly broadcasting a dandelion transaction (observe logs!!). Ensure that the transaction eventually transitions from the stempool into the real mempool.
>   * [x]  Validate Dandelion is enabled but normal transactions are still possible
> * [ ]  TODO-03: Confirm MultiAlgo Mining Working Properly
>   
>   * [x]  Mine sha256 block
>   * [ ]  Mine odocrypt block
>   * [x]  Mine Qubit block
>   * [x]  Mine Skien block
>   * [x]  Mine Scrypt block
> * [x]  TODO-04: Confirm All DGB Chain Specific Settings Set Properly
>   
>   * [x]  Confirm Buried Deployments
>   * [x]  Confirm Ports
>   * [x]  Confirm Protocol Version
>   * [x]  Confirm Client Version
>   * [x]  Confirm Seeds
>   * [x]  Confirm Checkpoints
> * [ ]  TODO-05: Confirm Taproot Deployment Set Properly & Tested
>   
>   * [x]   Set Taproot Activation Window
>   * [ ]  Test Taproot Activation
> * [ ]  TODO-06: Confirm DGB Signet Added Properly
>   
>   * [ ]  Set initial parameters
>   * [ ]  Test Signet
> * [ ]  TODO-07: Confirm 8.22 DGB GUI Working As Expecting
>   
>   * [ ]  Confirm Theme & Icons
>   * [x]  Confirm Send Coins Page
>   * [x]  Confirm Home Screen
>   * [x]  Update Version Image
>   * [x]  Confirm Receive Page
>   * [x]  Test GUI Multi Wallet Feature
> * [ ]  TODO-08: Confirm DGB Testnet Setup Properly & Reset
>   
>   * [ ]  Reset Testnet
>   * [ ]  Test mine all algos
>   * [ ]  Test taproot activation
> * [ ]  TODO-09: Finalize TX Fee Policy for DGB v8.22
>   
>   * [x]   Remove RBF
>   * [ ]   Determine Minimum DGB TX Fee
>   * [ ]  Test Fee Estimates
> * [ ]  TODO-10:  Fix All Unit Tests
> * [ ]  TODO-11:  Fix All Functional Tests
> * [ ]  TODO-12:  Fix All Util & Fuzz Tests
> * [ ]  TODO-12:  Finalize Supply Curve / Distribution Hard Cap Code
> * [ ]  TODO-13:  Optimize Initial Client Load Up Speed

**Comment by JohnnyLawDGB** [comment]
I have a fresh core wallet and would love to test 8.22. A little unclear as to how to do so. Point me in the right direction?

**Comment by saltedlolly** [comment]
It would be good to update this with where we are at.

**Comment by JaredTate** [comment]
IT looks like we need to discuss and finalize the following:

- Dandelion, fully test
- Signet
- Taproot, what do we want to do here?

We can fork branches once we are about to release the final 8.22 for feature branches.

**Comment by JaredTate** [comment]
Going to close this issue as in my opinion 8.22 is ready. We as a community just need to decide if we want to activate/upgrade taproot or not.
